sudo: false

language: java

jdk:
  - oraclejdk8

env:
  - TERM=dumb

notifications:
  email:
    recipients:
      - evelinec@ca.ibm.com
    on_success: never # default: change
    on_failure: always # default: always
  
before_install:
 - cd finish


install: mvn clean install
